import{r as e}from"./assets/rolldown-runtime-Cq0jCQ29.js";import{n as t,r as n,t as r}from"./assets/vendor-IymN8PWA.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin===`use-credentials`?t.credentials=`include`:e.crossOrigin===`anonymous`?t.credentials=`omit`:t.credentials=`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var i=e(n(),1),a=`55035088-7302bd2f5e79e745d79615534`,o=`https://pixabay.com/api/`;async function s(e,n=1){return(await t.get(o,{params:{key:a,q:e,image_type:`photo`,orientation:`horizontal`,safesearch:!0,page:n,per_page:15}})).data}var c=e(r(),1),l=document.querySelector(`.gallery`),u=document.querySelector(`.loader`),d=document.querySelector(`.load-more`),f;function p(e){let t=e.map(e=>`
    <li class="li-elem">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="status">
        <p class="status-item">Likes <span class="status-number">${e.likes}</span></p>
        <p class="status-item">Views <span class="status-number">${e.views}</span></p>
        <p class="status-item">Comments <span class="status-number">${e.comments}</span></p>
        <p class="status-item">Downloads <span class="status-number">${e.downloads}</span></p>
      </div>
    </li>
  `).join(``);l.insertAdjacentHTML(`beforeend`,t),f?f.refresh():f=new c.default(`.gallery a`,{captions:!0,captionsData:`alt`,captionDelay:250})}function m(){l.innerHTML=``}function h(){u.classList.add(`visible`)}function g(){u.classList.remove(`visible`)}function _(){d.classList.add(`visible`)}function v(){d.classList.remove(`visible`)}var y=document.querySelector(`.form`),b=document.querySelector(`.load-more`),x=1,S=``,C=0;y.addEventListener(`submit`,async e=>{e.preventDefault();let t=e.target.elements[`search-text`].value.trim();if(t){S=t,x=1,m(),v(),h();try{let e=await s(t);if(C=e.totalHits,e.hits.length===0){i.default.error({message:`Sorry, there are no images matching your search query. Please try again!`,position:`topRight`,maxWidth:432,class:`custom-toast`});return}p(e.hits),_()}catch{i.default.error({message:`Something went wrong`})}finally{g()}}}),b.addEventListener(`click`,async()=>{x+=1,h();try{p((await s(S,x)).hits),x*15>=C&&(v(),i.default.info({message:`We're sorry, but you've reached the end of search results.`}));let e=document.querySelector(`.li-elem`).getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:`smooth`})}catch{i.default.error({message:`Error`})}finally{g()}});
//# sourceMappingURL=index.js.map