import{a as w,S,i as n}from"./assets/vendor-CZFvrrFo.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&d(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const q="55035088-7302bd2f5e79e745d79615534",B="https://pixabay.com/api/";async function m(r,s=1){return(await w.get(B,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more");let c;function h(r){const s=r.map(e=>`
    <li class="li-elem">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="status">
        <p class="status-item">Likes <span class="status-number">${e.likes}</span></p>
        <p class="status-item">Views <span class="status-number">${e.views}</span></p>
        <p class="status-item">Comments <span class="status-number">${e.comments}</span></p>
        <p class="status-item">Downloads <span class="status-number">${e.downloads}</span></p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",s),c?c.refresh():c=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}function M(){f.innerHTML=""}function g(){p.classList.add("visible")}function L(){p.classList.remove("visible")}function P(){y.classList.add("visible")}function u(){y.classList.remove("visible")}const $=document.querySelector(".form"),x=document.querySelector(".load-more");let a=1,l="",b=0;const E=15;function v(r){a*E>=b?(u(),r>0&&n.info({message:"We're sorry, but you've reached the end of search results."})):r>0&&P()}$.addEventListener("submit",async r=>{r.preventDefault();const s=r.target.elements["search-text"].value.trim();if(s){l=s,a=1,M(),u(),g();try{const e=await m(l,a);if(b=e.totalHits,e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",maxWidth:432,class:"custom-toast"});return}h(e.hits),v(e.hits.length)}catch{n.error({message:"Something went wrong"})}finally{L()}}});x.addEventListener("click",async()=>{a+=1,u(),g();try{const r=await m(l,a);h(r.hits),v(r.hits.length);const s=document.querySelector(".li-elem");if(s){const e=s.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}catch{n.error({message:"Error"})}finally{L()}});
//# sourceMappingURL=index.js.map
