import{a as v,S as w,i as n}from"./assets/vendor-CZFvrrFo.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const S="55035088-7302bd2f5e79e745d79615534",q="https://pixabay.com/api/";async function u(o,s=1){return(await v.get(q,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}const d=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more");let c;function f(o){const s=o.map(e=>`
    <li class="li-elem">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="status">
        <p class="status-item">Likes <span class="status-number">${e.likes}</span></p>
        <p class="status-item">Views <span class="status-number">${e.views}</span></p>
        <p class="status-item">Comments <span class="status-number">${e.comments}</span></p>
        <p class="status-item">Downloads <span class="status-number">${e.downloads}</span></p>
      </div>
    </li>
  `).join("");d.insertAdjacentHTML("beforeend",s),c?c.refresh():c=new w(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}function B(){d.innerHTML=""}function y(){m.classList.add("visible")}function h(){m.classList.remove("visible")}function $(){p.classList.add("visible")}function g(){p.classList.remove("visible")}const M=document.querySelector(".form"),P=document.querySelector(".load-more");let a=1,L="",b=0;M.addEventListener("submit",async o=>{o.preventDefault();const s=o.target.elements["search-text"].value.trim();if(s){L=s,a=1,B(),g(),y();try{const e=await u(s);if(b=e.totalHits,e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",maxWidth:432,class:"custom-toast"});return}f(e.hits),$()}catch{n.error({message:"Something went wrong"})}finally{h()}}});P.addEventListener("click",async()=>{a+=1,y();try{const o=await u(L,a);f(o.hits),a*15>=b&&(g(),n.info({message:"We're sorry, but you've reached the end of search results."}));const e=document.querySelector(".li-elem").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch{n.error({message:"Error"})}finally{h()}});
//# sourceMappingURL=index.js.map
